
name: 'Kodo Upload Action'
description: 'Upload assets to kodo'
branding:
  icon: 'upload-cloud'
  color: 'yellow'
inputs:
  title:
    description: 'The title of the action'
    required: false
  bucket:
    required: false
  accessKey:
    required: false
  secretKey:
    required: true
  domain:
    required: true
  zone:
    required: true
  assets:
    required: true
  callbackUrlExpire:
    required: false
    default: 604800
  callback:
    required: false
runs:
  using: 'node20'
  main: 'lib/index.js'
